### ISSUE TITLE
Seafoam Islands Item not Highlighted

### ISSUE THREAD

**Issue by Kensairabbit37** [kelseyyoung/FRLGIronmonMap#11]
There's a regular item on the 2nd floor near ladder #6 that isn't highlighted by the "Highlight Regular Items" option.

![image](https://github.com/user-attachments/assets/f6d502e4-e7f4-44a5-968a-aa92be969ba5)

**Comment by kelseyyoung** [comment]
Thanks for reporting! This should now be fixed
