### ISSUE TITLE
Mismarked Biker on Route 8

### ISSUE THREAD

**Issue by Kensairabbit37** [kelseyyoung/FRLGIronmonMap#12]
Biker Ricardo on Route 8 is listed as having 3x Level 33 mons
Actually has 2x Level 33 and 1x Level 35 mons

**Comment by Kensairabbit37** [comment]
![image](https://github.com/user-attachments/assets/0657f060-3e1f-48c2-9bf6-837949153388)

**Comment by kelseyyoung** [comment]
Fixed! Thanks for reporting
