### ISSUE TITLE
Two trainers by the Seafoam Islands are mislabeled

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/FRLGIronmonMap#5]
![image](https://user-images.githubusercontent.com/20686777/192412684-5d14dacb-1b98-4c36-b1bc-db86e7433142.png)

I know you're aware of this to some extent, since there's a TODO comment for the swimmer without a name in trainers.ts.

The swimmer to the left in the picture is Swimmer Tiffany and the unlabeled trainer in the middle is Picnicker Irene who has 3 level 45 pokemon. The swimmer to the right is Swimmer Shirley who I guess actually is labeled, but the Picnicker Irene label is drawn over it.

I would've submitted a pull request, but I don't know the x and y for where Irene actually is, and I'm sure you can figure that out 100 times faster than I could.

Sources:
https://bulbapedia.bulbagarden.net/wiki/Kanto_Route_20#Generation_III_3
and 
https://www.serebii.net/pokearth/kanto/3rd/route20.shtml

**Comment by Ryan-Gole** [comment]
Also, I'm about to start playing Emerald ironmon, so I'm super excited that you already made the Emerald version of this 😄

**Comment by kelseyyoung** [comment]
Hey @Profesor-Caos thank you so much for pointing these out! As it would have it, I actually just fixed Picknicker Irene's tooltip a few hours ago. But I didn't know the name of that Swimmer so I'll add that asap!
