### ISSUE TITLE
Mislabelled trainers in Cinnabar mansion

### ISSUE THREAD

**Issue by bjosephpare** [kelseyyoung/FRLGIronmonMap#7]
the one you labelled BURGLAR LEWIS is actually BURGLAR ARNIE
the one labelled SCIENTIST IVAN is actually SCIENTEST BRAYDEN
the one labelled BURGLAR ARNIE is actually BURGLAR SIMON
SCIENTEIST BRAYDEN is actually SCIENTEST IVAN
BURGLAR SIMON is actually BURGLAR LEWIS

Two scientsts are swapped and three burglars are swapped in a sort of loop.
I think the data about # of mons is correct it's just the names.

**Comment by kelseyyoung** [comment]
thank you! this should be fixed
