### ISSUE TITLE
More mislabelled trainers

### ISSUE THREAD

**Issue by biterror** [kelseyyoung/FRLGIronmonMap#8]
I'm doing the open log community challenge so I will probably find all of these.
I'll alert here as I come across them. Thanks for making this awesome tool!

2 gentleman on boat have same name
swap hiker brice and hiker alan
I need to revisit Pokemon Tower channelers to tell you exactly which ones (I did not fight all of them), at least one of them was incorrect

**Comment by kelseyyoung** [comment]
thank you! I'll take a look at those two areas tomorrow when I get the chance, and I'll just leave this issue open if you find more

**Comment by biterror** [comment]
3 areas, I'll clarify a bit so it's easier

2 gentleman on boat are in rooms next to each other, just down and to the right of the entry from the dock
i forget where the hikers are but just swapping those 2 names fixes em
channeler that had wrong name i THINK is the one at the bottom of the heal pad room - there are more i did not fight yet

**Comment by kelseyyoung** [comment]
Everything above this comment should now be fixed. Took a pass thru pokemon tower and the bottom floor channelers were wrong as well

**Comment by bjosephpare** [comment]
Route 9 swap HIKER BRICE and HIKER ALAN

**Comment by bjosephpare** [comment]
Someone is telling me Hiker Brice and Allen are still swapped, on route 9

**Comment by JLeav** [comment]
I found the names for some trainers that aren't labeled:

Route 4: Lass -> Lass Crissy

Sliph Co Scientists:
2F: 3x42 --> Scientist Jerry
2F: 4x39 --> Scientist Connor
3F: --> Scientist Jose
4F: --> Scientist Rodney
5F: Juggler --> Juggler Dalton
5F: Scientist --> Scientist Beau
6F: --> Scientist Taylor
7F: --> Scientist Joshua
8F: --> Scientist Parker
9F: --> Scientist Ed
10F: --> Scientist Travis


I also have all but 2 pairs of rocket grunts' log numbers if those are wanted

**Comment by bjosephpare** [comment]
The circle of 4 swimmers below Fushia has some names mixed up
Below pallet Ronald and Wade are mixed

**Comment by kelseyyoung** [comment]
Thanks again so much for this info, these should now be fixed up to here. I'm going to close the issue for now and if anything else comes up please feel free to open another one
